// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package api

import (
	context "context"
	empty "github.com/golang/protobuf/ptypes/empty"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion7

// APIClient is the client API for API service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type APIClient interface {
	Get(ctx context.Context, in *Key, opts ...grpc.CallOption) (*Message, error)
	GetList(ctx context.Context, in *Key, opts ...grpc.CallOption) (API_GetListClient, error)
	Put(ctx context.Context, in *Message, opts ...grpc.CallOption) (*empty.Empty, error)
	PutList(ctx context.Context, opts ...grpc.CallOption) (API_PutListClient, error)
	Delete(ctx context.Context, in *Key, opts ...grpc.CallOption) (*empty.Empty, error)
	DeleteList(ctx context.Context, in *Key, opts ...grpc.CallOption) (*empty.Empty, error)
	Watch(ctx context.Context, opts ...grpc.CallOption) (API_WatchClient, error)
}

type aPIClient struct {
	cc grpc.ClientConnInterface
}

func NewAPIClient(cc grpc.ClientConnInterface) APIClient {
	return &aPIClient{cc}
}

func (c *aPIClient) Get(ctx context.Context, in *Key, opts ...grpc.CallOption) (*Message, error) {
	out := new(Message)
	err := c.cc.Invoke(ctx, "/api.API/Get", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aPIClient) GetList(ctx context.Context, in *Key, opts ...grpc.CallOption) (API_GetListClient, error) {
	stream, err := c.cc.NewStream(ctx, &_API_serviceDesc.Streams[0], "/api.API/GetList", opts...)
	if err != nil {
		return nil, err
	}
	x := &aPIGetListClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type API_GetListClient interface {
	Recv() (*Message, error)
	grpc.ClientStream
}

type aPIGetListClient struct {
	grpc.ClientStream
}

func (x *aPIGetListClient) Recv() (*Message, error) {
	m := new(Message)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *aPIClient) Put(ctx context.Context, in *Message, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/api.API/Put", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aPIClient) PutList(ctx context.Context, opts ...grpc.CallOption) (API_PutListClient, error) {
	stream, err := c.cc.NewStream(ctx, &_API_serviceDesc.Streams[1], "/api.API/PutList", opts...)
	if err != nil {
		return nil, err
	}
	x := &aPIPutListClient{stream}
	return x, nil
}

type API_PutListClient interface {
	Send(*Message) error
	CloseAndRecv() (*empty.Empty, error)
	grpc.ClientStream
}

type aPIPutListClient struct {
	grpc.ClientStream
}

func (x *aPIPutListClient) Send(m *Message) error {
	return x.ClientStream.SendMsg(m)
}

func (x *aPIPutListClient) CloseAndRecv() (*empty.Empty, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(empty.Empty)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *aPIClient) Delete(ctx context.Context, in *Key, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/api.API/Delete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aPIClient) DeleteList(ctx context.Context, in *Key, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/api.API/DeleteList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aPIClient) Watch(ctx context.Context, opts ...grpc.CallOption) (API_WatchClient, error) {
	stream, err := c.cc.NewStream(ctx, &_API_serviceDesc.Streams[2], "/api.API/Watch", opts...)
	if err != nil {
		return nil, err
	}
	x := &aPIWatchClient{stream}
	return x, nil
}

type API_WatchClient interface {
	Send(*Key) error
	Recv() (*Message, error)
	grpc.ClientStream
}

type aPIWatchClient struct {
	grpc.ClientStream
}

func (x *aPIWatchClient) Send(m *Key) error {
	return x.ClientStream.SendMsg(m)
}

func (x *aPIWatchClient) Recv() (*Message, error) {
	m := new(Message)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// APIServer is the server API for API service.
// All implementations must embed UnimplementedAPIServer
// for forward compatibility
type APIServer interface {
	Get(context.Context, *Key) (*Message, error)
	GetList(*Key, API_GetListServer) error
	Put(context.Context, *Message) (*empty.Empty, error)
	PutList(API_PutListServer) error
	Delete(context.Context, *Key) (*empty.Empty, error)
	DeleteList(context.Context, *Key) (*empty.Empty, error)
	Watch(API_WatchServer) error
	mustEmbedUnimplementedAPIServer()
}

// UnimplementedAPIServer must be embedded to have forward compatible implementations.
type UnimplementedAPIServer struct {
}

func (UnimplementedAPIServer) Get(context.Context, *Key) (*Message, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}
func (UnimplementedAPIServer) GetList(*Key, API_GetListServer) error {
	return status.Errorf(codes.Unimplemented, "method GetList not implemented")
}
func (UnimplementedAPIServer) Put(context.Context, *Message) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Put not implemented")
}
func (UnimplementedAPIServer) PutList(API_PutListServer) error {
	return status.Errorf(codes.Unimplemented, "method PutList not implemented")
}
func (UnimplementedAPIServer) Delete(context.Context, *Key) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Delete not implemented")
}
func (UnimplementedAPIServer) DeleteList(context.Context, *Key) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteList not implemented")
}
func (UnimplementedAPIServer) Watch(API_WatchServer) error {
	return status.Errorf(codes.Unimplemented, "method Watch not implemented")
}
func (UnimplementedAPIServer) mustEmbedUnimplementedAPIServer() {}

// UnsafeAPIServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to APIServer will
// result in compilation errors.
type UnsafeAPIServer interface {
	mustEmbedUnimplementedAPIServer()
}

func RegisterAPIServer(s *grpc.Server, srv APIServer) {
	s.RegisterService(&_API_serviceDesc, srv)
}

func _API_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Key)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APIServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.API/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APIServer).Get(ctx, req.(*Key))
	}
	return interceptor(ctx, in, info, handler)
}

func _API_GetList_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(Key)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(APIServer).GetList(m, &aPIGetListServer{stream})
}

type API_GetListServer interface {
	Send(*Message) error
	grpc.ServerStream
}

type aPIGetListServer struct {
	grpc.ServerStream
}

func (x *aPIGetListServer) Send(m *Message) error {
	return x.ServerStream.SendMsg(m)
}

func _API_Put_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Message)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APIServer).Put(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.API/Put",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APIServer).Put(ctx, req.(*Message))
	}
	return interceptor(ctx, in, info, handler)
}

func _API_PutList_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(APIServer).PutList(&aPIPutListServer{stream})
}

type API_PutListServer interface {
	SendAndClose(*empty.Empty) error
	Recv() (*Message, error)
	grpc.ServerStream
}

type aPIPutListServer struct {
	grpc.ServerStream
}

func (x *aPIPutListServer) SendAndClose(m *empty.Empty) error {
	return x.ServerStream.SendMsg(m)
}

func (x *aPIPutListServer) Recv() (*Message, error) {
	m := new(Message)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _API_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Key)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APIServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.API/Delete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APIServer).Delete(ctx, req.(*Key))
	}
	return interceptor(ctx, in, info, handler)
}

func _API_DeleteList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Key)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APIServer).DeleteList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.API/DeleteList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APIServer).DeleteList(ctx, req.(*Key))
	}
	return interceptor(ctx, in, info, handler)
}

func _API_Watch_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(APIServer).Watch(&aPIWatchServer{stream})
}

type API_WatchServer interface {
	Send(*Message) error
	Recv() (*Key, error)
	grpc.ServerStream
}

type aPIWatchServer struct {
	grpc.ServerStream
}

func (x *aPIWatchServer) Send(m *Message) error {
	return x.ServerStream.SendMsg(m)
}

func (x *aPIWatchServer) Recv() (*Key, error) {
	m := new(Key)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _API_serviceDesc = grpc.ServiceDesc{
	ServiceName: "api.API",
	HandlerType: (*APIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Get",
			Handler:    _API_Get_Handler,
		},
		{
			MethodName: "Put",
			Handler:    _API_Put_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _API_Delete_Handler,
		},
		{
			MethodName: "DeleteList",
			Handler:    _API_DeleteList_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetList",
			Handler:       _API_GetList_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "PutList",
			Handler:       _API_PutList_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "Watch",
			Handler:       _API_Watch_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "proto.proto",
}
